// Comprehensive Trivandrum One Seed Data
// Places, Screens, and User data

export const places = [
  // Food & Restaurants
  {
    id: 'place-001',
    name: 'Villa Maya',
    category: 'food',
    area: 'Airport Road',
    description: 'Luxury heritage restaurant offering authentic Kerala cuisine in a restored Dutch mansion. Features traditional recipes and colonial ambiance.',
    latitude: 8.4921,
    longitude: 76.9467,
    timing: '12:00 PM - 11:00 PM',
    phone: '+91 471 2501000',
    cuisines: ['Kerala', 'Indian', 'Continental'],
    priceRange: 'High',
    rating: 4.6,
    tags: ['heritage', 'luxury', 'romantic'],
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4'],
    amenities: ['Parking', 'Air Conditioned', 'WiFi', 'Family Friendly'],
  },
  {
    id: 'place-002',
    name: 'Zam Zam Restaurant',
    category: 'food',
    area: 'Palayam',
    description: 'Iconic restaurant serving authentic Malabar and Arabic cuisine since 1976. Famous for biryanis and grilled specialties.',
    latitude: 8.4932,
    longitude: 76.9547,
    timing: '11:00 AM - 11:00 PM',
    phone: '+91 471 2330080',
    cuisines: ['Arabic', 'Malabar', 'Indian'],
    priceRange: 'Medium',
    rating: 4.4,
    tags: ['family', 'halal', 'popular'],
    images: ['https://images.unsplash.com/photo-1555939594-58d7cb561ad1'],
    amenities: ['Parking', 'Takeaway', 'Family Seating'],
  },
  {
    id: 'place-003',
    name: 'Indian Coffee House',
    category: 'food',
    area: 'Statue Junction',
    description: 'Historic coffee house chain serving traditional South Indian breakfast and filter coffee in a nostalgic setting.',
    latitude: 8.4875,
    longitude: 76.9525,
    timing: '7:00 AM - 9:00 PM',
    phone: '+91 471 2333344',
    cuisines: ['South Indian', 'Snacks', 'Beverages'],
    priceRange: 'Budget',
    rating: 4.3,
    tags: ['heritage', 'breakfast', 'coffee'],
    images: ['https://images.unsplash.com/photo-1559496417-e7f25c8b92af'],
    amenities: ['WiFi', 'Student Friendly'],
  },
  {
    id: 'place-004',
    name: 'The French Toast',
    category: 'food',
    area: 'Vellayambalam',
    description: 'Trendy cafe serving continental breakfast, artisan coffee, and international cuisine in a cozy European-style ambiance.',
    latitude: 8.5201,
    longitude: 76.9367,
    timing: '8:00 AM - 10:00 PM',
    phone: '+91 471 4012345',
    cuisines: ['Continental', 'Cafe', 'Bakery'],
    priceRange: 'Medium',
    rating: 4.7,
    tags: ['cafe', 'breakfast', 'instagram-worthy'],
    images: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24'],
    amenities: ['WiFi', 'Air Conditioned', 'Pet Friendly', 'Outdoor Seating'],
  },

  // Medicine & Healthcare
  {
    id: 'place-005',
    name: 'Apollo Pharmacy',
    category: 'medicine',
    area: 'Statue Junction',
    description: '24/7 pharmacy chain offering prescription medicines, OTC drugs, healthcare products, and online consultation services.',
    latitude: 8.4878,
    longitude: 76.9520,
    timing: 'Open 24 Hours',
    phone: '+91 471 2727272',
    services: ['Prescription', 'OTC', 'Health Products', 'Home Delivery'],
    rating: 4.5,
    tags: ['24x7', 'emergency', 'trusted'],
    images: ['https://images.unsplash.com/photo-1587854692152-cbe660dbde88'],
  },
  {
    id: 'place-006',
    name: 'MedPlus Pharmacy',
    category: 'medicine',
    area: 'Kazhakootam',
    description: 'Reliable pharmacy chain with competitive pricing, home delivery, and health monitoring services.',
    latitude: 8.5819,
    longitude: 76.8713,
    timing: '8:00 AM - 11:00 PM',
    phone: '+91 471 2727373',
    services: ['Medicines', 'Lab Tests', 'Health Check', 'Consultation'],
    rating: 4.3,
    tags: ['affordable', 'delivery', 'health-check'],
    images: ['https://images.unsplash.com/photo-1576602976047-174e57a47881'],
  },
  {
    id: 'place-007',
    name: 'KIMS Hospital Pharmacy',
    category: 'medicine',
    area: 'Peroorkada',
    description: 'Hospital pharmacy providing specialized medicines, surgical supplies, and medical equipment. Expert pharmacist consultation available.',
    latitude: 8.5667,
    longitude: 76.8807,
    timing: 'Open 24 Hours',
    phone: '+91 471 3041000',
    services: ['Hospital Pharmacy', 'Specialized Drugs', 'Medical Equipment'],
    rating: 4.6,
    tags: ['hospital', '24x7', 'specialist'],
    images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926'],
  },

  // Tourist Spots
  {
    id: 'place-008',
    name: 'Padmanabhaswamy Temple',
    category: 'tourist',
    area: 'East Fort',
    description: 'Ancient Hindu temple dedicated to Lord Vishnu. Famous for Dravidian architecture and being one of the richest temples in the world.',
    latitude: 8.4826,
    longitude: 76.9494,
    timing: '3:30 AM - 12:00 PM, 5:00 PM - 8:00 PM',
    phone: '+91 471 2450233',
    entry: 'Dress code required',
    tags: ['heritage', 'religious', 'architecture', 'must-visit'],
    rating: 4.8,
    images: ['https://images.unsplash.com/photo-1564507592333-c60657eea523'],
  },
  {
    id: 'place-009',
    name: 'Kovalam Beach',
    category: 'tourist',
    area: 'Kovalam',
    description: 'World-famous crescent-shaped beach with golden sands, palm trees, and pristine waters. Perfect for swimming, surfing, and sunset views.',
    latitude: 8.4004,
    longitude: 76.9788,
    timing: 'Open 24 Hours',
    phone: '+91 471 2480085',
    entry: 'Free',
    tags: ['beach', 'swimming', 'sunset', 'photography'],
    rating: 4.7,
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e'],
    amenities: ['Beach Shacks', 'Water Sports', 'Lifeguard', 'Parking'],
  },
  {
    id: 'place-010',
    name: 'Napier Museum',
    category: 'tourist',
    area: 'Museum Road',
    description: 'Art and history museum featuring Indo-Saracenic architecture. Houses bronze idols, ancient ornaments, ivory carvings, and Kerala murals.',
    latitude: 8.5066,
    longitude: 76.9547,
    timing: '10:00 AM - 5:00 PM (Closed Monday)',
    phone: '+91 471 2318294',
    entry: 'Rs. 20 (Indians), Rs. 250 (Foreigners)',
    tags: ['museum', 'art', 'history', 'architecture'],
    rating: 4.4,
    images: ['https://images.unsplash.com/photo-1566127992631-137a642a90f4'],
  },
  {
    id: 'place-011',
    name: 'Ponmudi Hill Station',
    category: 'tourist',
    area: 'Ponmudi',
    description: 'Picturesque hill station at 1100m altitude featuring misty mountains, tea plantations, and scenic viewpoints. Ideal for trekking.',
    latitude: 8.7597,
    longitude: 77.1072,
    timing: 'Open 24 Hours',
    phone: '+91 471 2301132',
    entry: 'Free',
    tags: ['hill-station', 'trekking', 'nature', 'weekend-getaway'],
    rating: 4.6,
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4'],
    amenities: ['Trekking Trails', 'View Points', 'Tea Estates'],
  },

  // Shopping
  {
    id: 'place-012',
    name: 'Lulu Mall Trivandrum',
    category: 'shopping',
    area: 'Akkulam',
    description: 'Largest shopping mall in Kerala with 225+ stores, food court, multiplex, gaming zone, and entertainment center.',
    latitude: 8.5197,
    longitude: 76.9489,
    timing: '10:00 AM - 10:00 PM',
    phone: '+91 471 6696666',
    tags: ['mall', 'shopping', 'entertainment', 'dining'],
    rating: 4.5,
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8'],
    amenities: ['Food Court', 'Cinema', 'Parking', 'Kids Zone', 'Hypermarket'],
  },
  {
    id: 'place-013',
    name: 'Chalai Market',
    category: 'shopping',
    area: 'Chalai',
    description: 'Historic wholesale market offering textiles, jewelry, spices, electronics, and household items at competitive prices.',
    latitude: 8.4887,
    longitude: 76.9494,
    timing: '9:00 AM - 9:00 PM',
    phone: '+91 471 2323456',
    tags: ['market', 'wholesale', 'local', 'bargain'],
    rating: 4.2,
    images: ['https://images.unsplash.com/photo-1555529902-5261145633bf'],
  },

  // Emergency Services
  {
    id: 'place-014',
    name: 'Trivandrum Medical College Hospital',
    category: 'emergency',
    area: 'Medical College',
    description: 'Premier government medical college and tertiary care hospital with 24/7 emergency services, trauma care, and specialized departments.',
    latitude: 8.5241,
    longitude: 76.9366,
    timing: 'Open 24 Hours',
    phone: '+91 471 2528300',
    emergency: '108',
    services: ['Emergency', 'Trauma', 'ICU', 'Surgery', 'Specialized Care'],
    rating: 4.4,
    tags: ['hospital', '24x7', 'emergency', 'government'],
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d'],
  },
  {
    id: 'place-015',
    name: 'Police Station - Museum',
    category: 'emergency',
    area: 'Museum',
    description: 'City police station providing law enforcement, emergency response, and public safety services.',
    latitude: 8.5075,
    longitude: 76.9531,
    timing: 'Open 24 Hours',
    phone: '+91 471 2321547',
    emergency: '100',
    services: ['Emergency Response', 'FIR', 'Complaint', 'Women Safety'],
    rating: 4.0,
    tags: ['police', '24x7', 'safety', 'emergency'],
    images: ['https://images.unsplash.com/photo-1590736969955-71cc94901144'],
  },

  // Transport
  {
    id: 'place-016',
    name: 'East Fort KSRTC Bus Station',
    category: 'transport',
    area: 'East Fort',
    description: 'Main bus terminal for intercity and interstate services. Connects Trivandrum to major cities across Kerala and neighboring states.',
    latitude: 8.4837,
    longitude: 76.9493,
    timing: '5:00 AM - 11:00 PM',
    phone: '+91 471 2463886',
    services: ['Interstate Buses', 'City Buses', 'Ticket Booking', 'Waiting Hall'],
    tags: ['bus-station', 'public-transport', 'intercity'],
    rating: 3.9,
    images: ['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957'],
  },
];

export const screens = [
  {
    id: 'screen-001',
    locationName: 'East Fort Junction',
    area: 'East Fort',
    description: 'High-traffic junction screen with excellent visibility for commuters and tourists. Prime location near Padmanabhaswamy Temple.',
    latitude: 8.4835,
    longitude: 76.9495,
    orientation: 'landscape',
    dimensions: '20ft x 10ft',
    resolution: '1920x1080',
    dailyFootfallEst: 50000,
    screenType: 'LED',
    pricing: {
      perDay: 5000,
      perWeek: 30000,
      perMonth: 100000,
    },
    availabilityStatus: 'available',
    adSlotDuration: 10, // seconds
    images: ['https://images.unsplash.com/photo-1589519160732-57fc498494f8'],
    tags: ['high-traffic', 'temple-area', 'tourist-zone'],
  },
  {
    id: 'screen-002',
    locationName: 'Technopark Main Gate',
    area: 'Kazhakootam',
    description: 'Tech hub screen targeting IT professionals and young demographics. Located at the entrance of Asia\'s largest IT park.',
    latitude: 8.5542,
    longitude: 76.8794,
    orientation: 'portrait',
    dimensions: '10ft x 18ft',
    resolution: '1080x1920',
    dailyFootfallEst: 40000,
    screenType: 'LED',
    pricing: {
      perDay: 4000,
      perWeek: 25000,
      perMonth: 85000,
    },
    availabilityStatus: 'available',
    adSlotDuration: 10,
    images: ['https://images.unsplash.com/photo-1573164574230-db1d5e960238'],
    tags: ['tech-zone', 'professionals', 'high-income'],
  },
  {
    id: 'screen-003',
    locationName: 'Lulu Mall Entrance',
    area: 'Akkulam',
    description: 'Premium mall screen targeting shoppers and families. High dwell time with affluent audience demographics.',
    latitude: 8.5195,
    longitude: 76.9487,
    orientation: 'landscape',
    dimensions: '15ft x 8ft',
    resolution: '1920x1080',
    dailyFootfallEst: 35000,
    screenType: 'LED',
    pricing: {
      perDay: 6000,
      perWeek: 38000,
      perMonth: 130000,
    },
    availabilityStatus: 'available',
    adSlotDuration: 15,
    images: ['https://images.unsplash.com/photo-1582407947304-fd86f028f716'],
    tags: ['mall', 'family', 'shopping', 'premium'],
  },
  {
    id: 'screen-004',
    locationName: 'Medical College Junction',
    area: 'Ulloor',
    description: 'Healthcare zone screen with visibility to students, patients, and medical professionals. Near major hospitals and colleges.',
    latitude: 8.5238,
    longitude: 76.9363,
    orientation: 'landscape',
    dimensions: '18ft x 9ft',
    resolution: '1920x1080',
    dailyFootfallEst: 30000,
    screenType: 'LED',
    pricing: {
      perDay: 3500,
      perWeek: 22000,
      perMonth: 75000,
    },
    availabilityStatus: 'partially-booked',
    adSlotDuration: 10,
    images: ['https://images.unsplash.com/photo-1557804506-669a67965ba0'],
    tags: ['healthcare', 'students', 'professionals'],
  },
  {
    id: 'screen-005',
    locationName: 'Kovalam Beach Road',
    area: 'Kovalam',
    description: 'Tourist hotspot screen with international audience. Perfect for travel, hospitality, and lifestyle brands.',
    latitude: 8.4002,
    longitude: 76.9786,
    orientation: 'landscape',
    dimensions: '22ft x 12ft',
    resolution: '1920x1080',
    dailyFootfallEst: 25000,
    screenType: 'LED',
    pricing: {
      perDay: 4500,
      perWeek: 28000,
      perMonth: 95000,
    },
    availabilityStatus: 'available',
    adSlotDuration: 12,
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e'],
    tags: ['tourist', 'beach', 'international', 'leisure'],
  },
  {
    id: 'screen-006',
    locationName: 'Statue Junction',
    area: 'Palayam',
    description: 'Central business district screen with mixed audience. High visibility for all demographics and commuters.',
    latitude: 8.4878,
    longitude: 76.9522,
    orientation: 'portrait',
    dimensions: '12ft x 20ft',
    resolution: '1080x1920',
    dailyFootfallEst: 45000,
    screenType: 'LED',
    pricing: {
      perDay: 5500,
      perWeek: 35000,
      perMonth: 120000,
    },
    availabilityStatus: 'available',
    adSlotDuration: 10,
    images: ['https://images.unsplash.com/photo-1545558014-8692077e9b5c'],
    tags: ['cbd', 'business', 'mixed-audience', 'high-traffic'],
  },
];

export const campaigns = [
  {
    id: 'campaign-001',
    title: 'Kerala Tourism - Gods Own Country',
    brandId: 'brand-001',
    description: 'Promote Kerala tourism with scenic visuals and cultural experiences. Target tourists and travelers.',
    active: true,
    extraRewardEnabled: true,
    rewardCoins: 30,
    screenIds: ['screen-001', 'screen-005', 'screen-006'],
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'campaign-002',
    title: 'Lulu Hypermarket Grand Sale',
    brandId: 'brand-002',
    description: 'Year-end shopping festival with up to 70% off. Family-friendly offers and entertainment.',
    active: true,
    extraRewardEnabled: true,
    rewardCoins: 25,
    screenIds: ['screen-003'],
    startDate: '2025-01-15',
    endDate: '2025-01-31',
    createdAt: new Date().toISOString(),
  },
];

export const brands = [
  {
    id: 'brand-001',
    name: 'Kerala Tourism',
    description: 'Official tourism board promoting Kerala as a travel destination',
    address: 'Park View, Thiruvananthapuram',
    latitude: 8.5241,
    longitude: 76.9366,
    phone: '+91 471 2321132',
    socials: {
      website: 'https://www.keralatourism.org',
      facebook: 'keralatourism',
      instagram: 'keralatourism',
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'brand-002',
    name: 'Lulu International Shopping Mall',
    description: 'Largest shopping mall in Kerala with 225+ stores',
    address: 'Akkulam, Thiruvananthapuram',
    latitude: 8.5197,
    longitude: 76.9489,
    phone: '+91 471 6696666',
    socials: {
      website: 'https://www.lulumall.in',
      facebook: 'lulumallthiruvananthapuram',
      instagram: 'lulumall_kerala',
    },
    createdAt: new Date().toISOString(),
  },
];
